name = "LogicalMechanism/convert_expression"
version = "0.2.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'LogicalMechanism/convert_expression'"

[repository]
user = "aiken-lag"
project = "convert_expression"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "main"
source = "github"